### ISSUE TITLE
Missing calibration file

### ISSUE THREAD

**Issue by SkyrimYun** [Haram-kim/Globally_Aligned_Events#1]
Hi Kim!
Thanks for your effort to build this repo!
In your personal page related to this repo https://haram-kim.github.io/Globally_Aligned_Events/
inside the dataset "ESIM_panorama", it seems that the camera calibration file 'pinhole_mono_nodistort_backward.yaml' is missing which is mentioned in the configuration file ''panorama.conf". I have checked the ESIM repo, this calibration file is not the default one. Could you please also provide the calibration file  'pinhole_mono_nodistort_backward.yaml'? 
Appreciate it a lot!

**Comment by Haram-kim** [comment]
Hello, Yun

In panorama data, the camera parameters of
'pinhole_mono_nodistort_backward' are the same as that of
'pinhole_mono_nodistort of opengl'.
The only difference is the initial orientation of the camera. (the camera
rotated 180 degrees with respect to Y-axis).
Unfortunately, I lost the yaml file while formatting my laptop. I will
restore the yaml file and organize data sets later.
The paper of the published code is under review now. Since, other work is
in progress, I think the data sets will be re-organized when the decision
comes out.

If you have any other questions, feel free to ask me!
Thank you.

Best regards,
Haram kim
ᐧ

2021년 4월 28일 (수) 오전 1:18, SkyrimYun ***@***.***>님이 작성:

**Comment by SkyrimYun** [comment]
Hi Haram

Thanks for your reply!
My name is Yunfan Yang, a master student in TU Berlin.
I am currently working on event-based SLAM (3-DOF) methods comparison as the topic of my master thesis.
My master thesis is under the guide of Prof. Guillermo Gallego and he recommends your project “globally aligned events” to me as one participant in the comparison.
Thanks for your help in the last email! Now I can build and configure the project and it is working well.

When I looked through the datasets you put at https://haram-kim.github.io/Globally_Aligned_Events/, I found that inside datasets ‘360-indoor’ and ‘fast-motion’, there are no ground truth poses.
I noticed that a motion capture system should be applied to obtain the ground truth poses. Could you please provide the ground truth poses for those two datasets so I can use them for evaluation?

Thanks a lot for your help!

Best wishes
Yunfan

发件人: Haram ***@***.***>
发送时间: 2021年4月28日 7:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Haram-kim/Globally_Aligned_Events] Missing calibration file (#1)

Hello, Yun

In panorama data, the camera parameters of
'pinhole_mono_nodistort_backward' are the same as that of
'pinhole_mono_nodistort of opengl'.
The only difference is the initial orientation of the camera. (the camera
rotated 180 degrees with respect to Y-axis).
Unfortunately, I lost the yaml file while formatting my laptop. I will
restore the yaml file and organize data sets later.
The paper of the published code is under review now. Since, other work is
in progress, I think the data sets will be re-organized when the decision
comes out.

If you have any other questions, feel free to ask me!
Thank you.

Best regards,
Haram kim
ᐧ

2021년 4월 28일 (수) 오전 1:18, SkyrimYun ***@***.***>님이 작성:

**Comment by Haram-kim** [comment]
Hi Yun, nice to get back to you.

Of course, the sequences have ground truth pose estimated with the VICON
tracker.
The correction of the data set might be finished by July 1st or earlier.

Thanks for your interest in my research and let me know if you have any
other questions on my work.

Best regards,
Haram Kim

2021년 6월 16일 (수) 오후 6:54, SkyrimYun ***@***.***>님이 작성:
