### ISSUE TITLE
Is camera coordinate system  aligned with the IMU?

### ISSUE THREAD

**Issue by Norton-z** [Haram-kim/Globally_Aligned_Events#3]
Is camera coordinate system  aligned with the IMU coordinate system? What are the three axes of the camera coordinate system direction?

**Comment by Haram-kim** [comment]
Yes, camera coordinate system is aligned with the IMU coordinate system. You can also refer the data sheet of DAVIS240C. 
The camera coordinate system direction is same with the figures in following url: https://docs.nvidia.com/isaac/isaac/packages/perception/doc/coord_frame.html.
